// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Analytics API (analytics/v3)
// Generated from:
//   Version: v3
//   Revision: 20170807
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_ANALYTICS_API_ACCOUNT_H_
#define  GOOGLE_ANALYTICS_API_ACCOUNT_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/client/util/date_time.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_analytics_api {
using namespace googleapis;

/**
 * JSON template for Analytics account entry.
 *
 * @ingroup DataObject
 */
class Account : public client::JsonCppData {
 public:
  /**
   * Child link for an account entry. Points to the list of web properties for
   * this account.
   *
   * @ingroup DataObject
   */
  class AccountChildLink : public client::JsonCppData {
   public:
    /**
     * Creates a new default instance.
     *
     * @return Ownership is passed back to the caller.
     */
    static AccountChildLink* New();

    /**
     * Standard constructor for an immutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit AccountChildLink(const Json::Value& storage);

    /**
     * Standard constructor for a mutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit AccountChildLink(Json::Value* storage);

    /**
     * Standard destructor.
     */
    virtual ~AccountChildLink();

    /**
     * Returns a string denoting the type of this data object.
     *
     * @return <code>google_analytics_api::AccountChildLink</code>
     */
    const char* GetTypeName() const {
      return "google_analytics_api::AccountChildLink";
    }

    /**
     * Determine if the '<code>href</code>' attribute was set.
     *
     * @return true if the '<code>href</code>' attribute was set.
     */
    bool has_href() const {
      return Storage().isMember("href");
    }

    /**
     * Clears the '<code>href</code>' attribute.
     */
    void clear_href() {
      MutableStorage()->removeMember("href");
    }


    /**
     * Get the value of the '<code>href</code>' attribute.
     */
    const StringPiece get_href() const {
      const Json::Value& v = Storage("href");
      if (v == Json::Value::null) return StringPiece("");
      return StringPiece(v.asCString());
    }

    /**
     * Change the '<code>href</code>' attribute.
     *
     * Link to the list of web properties for this account.
     *
     * @param[in] value The new value.
     */
    void set_href(const StringPiece& value) {
      *MutableStorage("href") = value.data();
    }

    /**
     * Determine if the '<code>type</code>' attribute was set.
     *
     * @return true if the '<code>type</code>' attribute was set.
     */
    bool has_type() const {
      return Storage().isMember("type");
    }

    /**
     * Clears the '<code>type</code>' attribute.
     */
    void clear_type() {
      MutableStorage()->removeMember("type");
    }


    /**
     * Get the value of the '<code>type</code>' attribute.
     */
    const StringPiece get_type() const {
      const Json::Value& v = Storage("type");
      if (v == Json::Value::null) return StringPiece("");
      return StringPiece(v.asCString());
    }

    /**
     * Change the '<code>type</code>' attribute.
     *
     * Type of the child link. Its value is "analytics#webproperties".
     *
     * @param[in] value The new value.
     */
    void set_type(const StringPiece& value) {
      *MutableStorage("type") = value.data();
    }

   private:
    void operator=(const AccountChildLink&);
  };  // AccountChildLink
  /**
   * Permissions the user has for this account.
   *
   * @ingroup DataObject
   */
  class AccountPermissions : public client::JsonCppData {
   public:
    /**
     * Creates a new default instance.
     *
     * @return Ownership is passed back to the caller.
     */
    static AccountPermissions* New();

    /**
     * Standard constructor for an immutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit AccountPermissions(const Json::Value& storage);

    /**
     * Standard constructor for a mutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit AccountPermissions(Json::Value* storage);

    /**
     * Standard destructor.
     */
    virtual ~AccountPermissions();

    /**
     * Returns a string denoting the type of this data object.
     *
     * @return <code>google_analytics_api::AccountPermissions</code>
     */
    const char* GetTypeName() const {
      return "google_analytics_api::AccountPermissions";
    }

    /**
     * Determine if the '<code>effective</code>' attribute was set.
     *
     * @return true if the '<code>effective</code>' attribute was set.
     */
    bool has_effective() const {
      return Storage().isMember("effective");
    }

    /**
     * Clears the '<code>effective</code>' attribute.
     */
    void clear_effective() {
      MutableStorage()->removeMember("effective");
    }


    /**
     * Get a reference to the value of the '<code>effective</code>' attribute.
     */
    const client::JsonCppArray<string > get_effective() const {
       const Json::Value& storage = Storage("effective");
      return client::JsonValueToCppValueHelper<client::JsonCppArray<string > >(storage);
    }

    /**
     * Gets a reference to a mutable value of the '<code>effective</code>'
     * property.
     *
     * All the permissions that the user has for this account. These include any
     * implied permissions (e.g., EDIT implies VIEW).
     *
     * @return The result can be modified to change the attribute value.
     */
    client::JsonCppArray<string > mutable_effective() {
      Json::Value* storage = MutableStorage("effective");
      return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<string > >(storage);
    }

   private:
    void operator=(const AccountPermissions&);
  };  // AccountPermissions
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Account* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Account(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Account(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Account();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_analytics_api::Account</code>
   */
  const char* GetTypeName() const {
    return "google_analytics_api::Account";
  }

  /**
   * Determine if the '<code>childLink</code>' attribute was set.
   *
   * @return true if the '<code>childLink</code>' attribute was set.
   */
  bool has_child_link() const {
    return Storage().isMember("childLink");
  }

  /**
   * Clears the '<code>childLink</code>' attribute.
   */
  void clear_child_link() {
    MutableStorage()->removeMember("childLink");
  }


  /**
   * Get a reference to the value of the '<code>childLink</code>' attribute.
   */
  const AccountChildLink get_child_link() const {
     const Json::Value& storage = Storage("childLink");
    return client::JsonValueToCppValueHelper<AccountChildLink >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>childLink</code>'
   * property.
   *
   * Child link for an account entry. Points to the list of web properties for
   * this account.
   *
   * @return The result can be modified to change the attribute value.
   */
  AccountChildLink mutable_childLink() {
    Json::Value* storage = MutableStorage("childLink");
    return client::JsonValueToMutableCppValueHelper<AccountChildLink >(storage);
  }

  /**
   * Determine if the '<code>created</code>' attribute was set.
   *
   * @return true if the '<code>created</code>' attribute was set.
   */
  bool has_created() const {
    return Storage().isMember("created");
  }

  /**
   * Clears the '<code>created</code>' attribute.
   */
  void clear_created() {
    MutableStorage()->removeMember("created");
  }


  /**
   * Get the value of the '<code>created</code>' attribute.
   */
  client::DateTime get_created() const {
    const Json::Value& storage = Storage("created");
    return client::JsonValueToCppValueHelper<client::DateTime >(storage);
  }

  /**
   * Change the '<code>created</code>' attribute.
   *
   * Time the account was created.
   *
   * @param[in] value The new value.
   */
  void set_created(client::DateTime value) {
    client::SetJsonValueFromCppValueHelper<client::DateTime >(
      value, MutableStorage("created"));
  }

  /**
   * Determine if the '<code>id</code>' attribute was set.
   *
   * @return true if the '<code>id</code>' attribute was set.
   */
  bool has_id() const {
    return Storage().isMember("id");
  }

  /**
   * Clears the '<code>id</code>' attribute.
   */
  void clear_id() {
    MutableStorage()->removeMember("id");
  }


  /**
   * Get the value of the '<code>id</code>' attribute.
   */
  const StringPiece get_id() const {
    const Json::Value& v = Storage("id");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>id</code>' attribute.
   *
   * Account ID.
   *
   * @param[in] value The new value.
   */
  void set_id(const StringPiece& value) {
    *MutableStorage("id") = value.data();
  }

  /**
   * Determine if the '<code>kind</code>' attribute was set.
   *
   * @return true if the '<code>kind</code>' attribute was set.
   */
  bool has_kind() const {
    return Storage().isMember("kind");
  }

  /**
   * Clears the '<code>kind</code>' attribute.
   */
  void clear_kind() {
    MutableStorage()->removeMember("kind");
  }


  /**
   * Get the value of the '<code>kind</code>' attribute.
   */
  const StringPiece get_kind() const {
    const Json::Value& v = Storage("kind");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>kind</code>' attribute.
   *
   * Resource type for Analytics account.
   *
   * @param[in] value The new value.
   */
  void set_kind(const StringPiece& value) {
    *MutableStorage("kind") = value.data();
  }

  /**
   * Determine if the '<code>name</code>' attribute was set.
   *
   * @return true if the '<code>name</code>' attribute was set.
   */
  bool has_name() const {
    return Storage().isMember("name");
  }

  /**
   * Clears the '<code>name</code>' attribute.
   */
  void clear_name() {
    MutableStorage()->removeMember("name");
  }


  /**
   * Get the value of the '<code>name</code>' attribute.
   */
  const StringPiece get_name() const {
    const Json::Value& v = Storage("name");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>name</code>' attribute.
   *
   * Account name.
   *
   * @param[in] value The new value.
   */
  void set_name(const StringPiece& value) {
    *MutableStorage("name") = value.data();
  }

  /**
   * Determine if the '<code>permissions</code>' attribute was set.
   *
   * @return true if the '<code>permissions</code>' attribute was set.
   */
  bool has_permissions() const {
    return Storage().isMember("permissions");
  }

  /**
   * Clears the '<code>permissions</code>' attribute.
   */
  void clear_permissions() {
    MutableStorage()->removeMember("permissions");
  }


  /**
   * Get a reference to the value of the '<code>permissions</code>' attribute.
   */
  const AccountPermissions get_permissions() const {
     const Json::Value& storage = Storage("permissions");
    return client::JsonValueToCppValueHelper<AccountPermissions >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>permissions</code>'
   * property.
   *
   * Permissions the user has for this account.
   *
   * @return The result can be modified to change the attribute value.
   */
  AccountPermissions mutable_permissions() {
    Json::Value* storage = MutableStorage("permissions");
    return client::JsonValueToMutableCppValueHelper<AccountPermissions >(storage);
  }

  /**
   * Determine if the '<code>selfLink</code>' attribute was set.
   *
   * @return true if the '<code>selfLink</code>' attribute was set.
   */
  bool has_self_link() const {
    return Storage().isMember("selfLink");
  }

  /**
   * Clears the '<code>selfLink</code>' attribute.
   */
  void clear_self_link() {
    MutableStorage()->removeMember("selfLink");
  }


  /**
   * Get the value of the '<code>selfLink</code>' attribute.
   */
  const StringPiece get_self_link() const {
    const Json::Value& v = Storage("selfLink");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>selfLink</code>' attribute.
   *
   * Link for this account.
   *
   * @param[in] value The new value.
   */
  void set_self_link(const StringPiece& value) {
    *MutableStorage("selfLink") = value.data();
  }

  /**
   * Determine if the '<code>starred</code>' attribute was set.
   *
   * @return true if the '<code>starred</code>' attribute was set.
   */
  bool has_starred() const {
    return Storage().isMember("starred");
  }

  /**
   * Clears the '<code>starred</code>' attribute.
   */
  void clear_starred() {
    MutableStorage()->removeMember("starred");
  }


  /**
   * Get the value of the '<code>starred</code>' attribute.
   */
  bool get_starred() const {
    const Json::Value& storage = Storage("starred");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>starred</code>' attribute.
   *
   * Indicates whether this account is starred or not.
   *
   * @param[in] value The new value.
   */
  void set_starred(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("starred"));
  }

  /**
   * Determine if the '<code>updated</code>' attribute was set.
   *
   * @return true if the '<code>updated</code>' attribute was set.
   */
  bool has_updated() const {
    return Storage().isMember("updated");
  }

  /**
   * Clears the '<code>updated</code>' attribute.
   */
  void clear_updated() {
    MutableStorage()->removeMember("updated");
  }


  /**
   * Get the value of the '<code>updated</code>' attribute.
   */
  client::DateTime get_updated() const {
    const Json::Value& storage = Storage("updated");
    return client::JsonValueToCppValueHelper<client::DateTime >(storage);
  }

  /**
   * Change the '<code>updated</code>' attribute.
   *
   * Time the account was last modified.
   *
   * @param[in] value The new value.
   */
  void set_updated(client::DateTime value) {
    client::SetJsonValueFromCppValueHelper<client::DateTime >(
      value, MutableStorage("updated"));
  }

 private:
  void operator=(const Account&);
};  // Account
}  // namespace google_analytics_api
#endif  // GOOGLE_ANALYTICS_API_ACCOUNT_H_
