// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Analytics API (analytics/v3)
// Generated from:
//   Version: v3
//   Revision: 20170807
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_ANALYTICS_API_AD_WORDS_ACCOUNT_H_
#define  GOOGLE_ANALYTICS_API_AD_WORDS_ACCOUNT_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_analytics_api {
using namespace googleapis;

/**
 * JSON template for an AdWords account.
 *
 * @ingroup DataObject
 */
class AdWordsAccount : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static AdWordsAccount* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit AdWordsAccount(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit AdWordsAccount(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~AdWordsAccount();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_analytics_api::AdWordsAccount</code>
   */
  const char* GetTypeName() const {
    return "google_analytics_api::AdWordsAccount";
  }

  /**
   * Determine if the '<code>autoTaggingEnabled</code>' attribute was set.
   *
   * @return true if the '<code>autoTaggingEnabled</code>' attribute was set.
   */
  bool has_auto_tagging_enabled() const {
    return Storage().isMember("autoTaggingEnabled");
  }

  /**
   * Clears the '<code>autoTaggingEnabled</code>' attribute.
   */
  void clear_auto_tagging_enabled() {
    MutableStorage()->removeMember("autoTaggingEnabled");
  }


  /**
   * Get the value of the '<code>autoTaggingEnabled</code>' attribute.
   */
  bool get_auto_tagging_enabled() const {
    const Json::Value& storage = Storage("autoTaggingEnabled");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>autoTaggingEnabled</code>' attribute.
   *
   * True if auto-tagging is enabled on the AdWords account. Read-only after the
   * insert operation.
   *
   * @param[in] value The new value.
   */
  void set_auto_tagging_enabled(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("autoTaggingEnabled"));
  }

  /**
   * Determine if the '<code>customerId</code>' attribute was set.
   *
   * @return true if the '<code>customerId</code>' attribute was set.
   */
  bool has_customer_id() const {
    return Storage().isMember("customerId");
  }

  /**
   * Clears the '<code>customerId</code>' attribute.
   */
  void clear_customer_id() {
    MutableStorage()->removeMember("customerId");
  }


  /**
   * Get the value of the '<code>customerId</code>' attribute.
   */
  const StringPiece get_customer_id() const {
    const Json::Value& v = Storage("customerId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>customerId</code>' attribute.
   *
   * Customer ID. This field is required when creating an AdWords link.
   *
   * @param[in] value The new value.
   */
  void set_customer_id(const StringPiece& value) {
    *MutableStorage("customerId") = value.data();
  }

  /**
   * Determine if the '<code>kind</code>' attribute was set.
   *
   * @return true if the '<code>kind</code>' attribute was set.
   */
  bool has_kind() const {
    return Storage().isMember("kind");
  }

  /**
   * Clears the '<code>kind</code>' attribute.
   */
  void clear_kind() {
    MutableStorage()->removeMember("kind");
  }


  /**
   * Get the value of the '<code>kind</code>' attribute.
   */
  const StringPiece get_kind() const {
    const Json::Value& v = Storage("kind");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>kind</code>' attribute.
   *
   * Resource type for AdWords account.
   *
   * @param[in] value The new value.
   */
  void set_kind(const StringPiece& value) {
    *MutableStorage("kind") = value.data();
  }

 private:
  void operator=(const AdWordsAccount&);
};  // AdWordsAccount
}  // namespace google_analytics_api
#endif  // GOOGLE_ANALYTICS_API_AD_WORDS_ACCOUNT_H_
