// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Analytics API (analytics/v3)
// Description:
//   Views and manages your Google Analytics data.
// Classes:
//   EntityAdWordsLink
// Documentation:
//   https://developers.google.com/analytics/

#include "google/analytics_api/entity_ad_words_link.h"
#include <string>
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/analytics_api/ad_words_account.h"
#include "google/analytics_api/web_property_ref.h"


#include <string>
#include "googleapis/strings/strcat.h"

namespace google_analytics_api {
using namespace googleapis;



// Object factory method (static).
EntityAdWordsLink::EntityAdWordsLinkEntity* EntityAdWordsLink::EntityAdWordsLinkEntity::New() {
  return new client::JsonCppCapsule<EntityAdWordsLinkEntity>;
}

// Standard immutable constructor.
EntityAdWordsLink::EntityAdWordsLinkEntity::EntityAdWordsLinkEntity(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
EntityAdWordsLink::EntityAdWordsLinkEntity::EntityAdWordsLinkEntity(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
EntityAdWordsLink::EntityAdWordsLinkEntity::~EntityAdWordsLinkEntity() {
}

// Properties.

const WebPropertyRef EntityAdWordsLink::EntityAdWordsLinkEntity::get_web_property_ref() const {
   const Json::Value& storage = Storage("webPropertyRef");
   return client::JsonValueToCppValueHelper<WebPropertyRef >(storage);
}

WebPropertyRef EntityAdWordsLink::EntityAdWordsLinkEntity::mutable_webPropertyRef() {
  Json::Value* storage = MutableStorage("webPropertyRef");
  return client::JsonValueToMutableCppValueHelper<WebPropertyRef >(storage);
}
// Object factory method (static).
EntityAdWordsLink* EntityAdWordsLink::New() {
  return new client::JsonCppCapsule<EntityAdWordsLink>;
}

// Standard immutable constructor.
EntityAdWordsLink::EntityAdWordsLink(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
EntityAdWordsLink::EntityAdWordsLink(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
EntityAdWordsLink::~EntityAdWordsLink() {
}

// Properties.

const client::JsonCppArray<AdWordsAccount > EntityAdWordsLink::get_ad_words_accounts() const {
   const Json::Value& storage = Storage("adWordsAccounts");
   return client::JsonValueToCppValueHelper<client::JsonCppArray<AdWordsAccount > >(storage);
}

client::JsonCppArray<AdWordsAccount > EntityAdWordsLink::mutable_adWordsAccounts() {
  Json::Value* storage = MutableStorage("adWordsAccounts");
  return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<AdWordsAccount > >(storage);
}
}  // namespace google_analytics_api
