// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Analytics API (analytics/v3)
// Generated from:
//   Version: v3
//   Revision: 20170807
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_ANALYTICS_API_WEB_PROPERTY_SUMMARY_H_
#define  GOOGLE_ANALYTICS_API_WEB_PROPERTY_SUMMARY_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/analytics_api/profile_summary.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_analytics_api {
using namespace googleapis;

/**
 * JSON template for an Analytics WebPropertySummary. WebPropertySummary returns
 * basic information (i.e., summary) for a web property.
 *
 * @ingroup DataObject
 */
class WebPropertySummary : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static WebPropertySummary* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit WebPropertySummary(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit WebPropertySummary(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~WebPropertySummary();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_analytics_api::WebPropertySummary</code>
   */
  const char* GetTypeName() const {
    return "google_analytics_api::WebPropertySummary";
  }

  /**
   * Determine if the '<code>id</code>' attribute was set.
   *
   * @return true if the '<code>id</code>' attribute was set.
   */
  bool has_id() const {
    return Storage().isMember("id");
  }

  /**
   * Clears the '<code>id</code>' attribute.
   */
  void clear_id() {
    MutableStorage()->removeMember("id");
  }


  /**
   * Get the value of the '<code>id</code>' attribute.
   */
  const StringPiece get_id() const {
    const Json::Value& v = Storage("id");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>id</code>' attribute.
   *
   * Web property ID of the form UA-XXXXX-YY.
   *
   * @param[in] value The new value.
   */
  void set_id(const StringPiece& value) {
    *MutableStorage("id") = value.data();
  }

  /**
   * Determine if the '<code>internalWebPropertyId</code>' attribute was set.
   *
   * @return true if the '<code>internalWebPropertyId</code>' attribute was set.
   */
  bool has_internal_web_property_id() const {
    return Storage().isMember("internalWebPropertyId");
  }

  /**
   * Clears the '<code>internalWebPropertyId</code>' attribute.
   */
  void clear_internal_web_property_id() {
    MutableStorage()->removeMember("internalWebPropertyId");
  }


  /**
   * Get the value of the '<code>internalWebPropertyId</code>' attribute.
   */
  const StringPiece get_internal_web_property_id() const {
    const Json::Value& v = Storage("internalWebPropertyId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>internalWebPropertyId</code>' attribute.
   *
   * Internal ID for this web property.
   *
   * @param[in] value The new value.
   */
  void set_internal_web_property_id(const StringPiece& value) {
    *MutableStorage("internalWebPropertyId") = value.data();
  }

  /**
   * Determine if the '<code>kind</code>' attribute was set.
   *
   * @return true if the '<code>kind</code>' attribute was set.
   */
  bool has_kind() const {
    return Storage().isMember("kind");
  }

  /**
   * Clears the '<code>kind</code>' attribute.
   */
  void clear_kind() {
    MutableStorage()->removeMember("kind");
  }


  /**
   * Get the value of the '<code>kind</code>' attribute.
   */
  const StringPiece get_kind() const {
    const Json::Value& v = Storage("kind");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>kind</code>' attribute.
   *
   * Resource type for Analytics WebPropertySummary.
   *
   * @param[in] value The new value.
   */
  void set_kind(const StringPiece& value) {
    *MutableStorage("kind") = value.data();
  }

  /**
   * Determine if the '<code>level</code>' attribute was set.
   *
   * @return true if the '<code>level</code>' attribute was set.
   */
  bool has_level() const {
    return Storage().isMember("level");
  }

  /**
   * Clears the '<code>level</code>' attribute.
   */
  void clear_level() {
    MutableStorage()->removeMember("level");
  }


  /**
   * Get the value of the '<code>level</code>' attribute.
   */
  const StringPiece get_level() const {
    const Json::Value& v = Storage("level");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>level</code>' attribute.
   *
   * Level for this web property. Possible values are STANDARD or PREMIUM.
   *
   * @param[in] value The new value.
   */
  void set_level(const StringPiece& value) {
    *MutableStorage("level") = value.data();
  }

  /**
   * Determine if the '<code>name</code>' attribute was set.
   *
   * @return true if the '<code>name</code>' attribute was set.
   */
  bool has_name() const {
    return Storage().isMember("name");
  }

  /**
   * Clears the '<code>name</code>' attribute.
   */
  void clear_name() {
    MutableStorage()->removeMember("name");
  }


  /**
   * Get the value of the '<code>name</code>' attribute.
   */
  const StringPiece get_name() const {
    const Json::Value& v = Storage("name");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>name</code>' attribute.
   *
   * Web property name.
   *
   * @param[in] value The new value.
   */
  void set_name(const StringPiece& value) {
    *MutableStorage("name") = value.data();
  }

  /**
   * Determine if the '<code>profiles</code>' attribute was set.
   *
   * @return true if the '<code>profiles</code>' attribute was set.
   */
  bool has_profiles() const {
    return Storage().isMember("profiles");
  }

  /**
   * Clears the '<code>profiles</code>' attribute.
   */
  void clear_profiles() {
    MutableStorage()->removeMember("profiles");
  }


  /**
   * Get a reference to the value of the '<code>profiles</code>' attribute.
   */
  const client::JsonCppArray<ProfileSummary > get_profiles() const;

  /**
   * Gets a reference to a mutable value of the '<code>profiles</code>'
   * property.
   *
   * List of profiles under this web property.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<ProfileSummary > mutable_profiles();

  /**
   * Determine if the '<code>starred</code>' attribute was set.
   *
   * @return true if the '<code>starred</code>' attribute was set.
   */
  bool has_starred() const {
    return Storage().isMember("starred");
  }

  /**
   * Clears the '<code>starred</code>' attribute.
   */
  void clear_starred() {
    MutableStorage()->removeMember("starred");
  }


  /**
   * Get the value of the '<code>starred</code>' attribute.
   */
  bool get_starred() const {
    const Json::Value& storage = Storage("starred");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>starred</code>' attribute.
   *
   * Indicates whether this web property is starred or not.
   *
   * @param[in] value The new value.
   */
  void set_starred(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("starred"));
  }

  /**
   * Determine if the '<code>websiteUrl</code>' attribute was set.
   *
   * @return true if the '<code>websiteUrl</code>' attribute was set.
   */
  bool has_website_url() const {
    return Storage().isMember("websiteUrl");
  }

  /**
   * Clears the '<code>websiteUrl</code>' attribute.
   */
  void clear_website_url() {
    MutableStorage()->removeMember("websiteUrl");
  }


  /**
   * Get the value of the '<code>websiteUrl</code>' attribute.
   */
  const StringPiece get_website_url() const {
    const Json::Value& v = Storage("websiteUrl");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>websiteUrl</code>' attribute.
   *
   * Website url for this web property.
   *
   * @param[in] value The new value.
   */
  void set_website_url(const StringPiece& value) {
    *MutableStorage("websiteUrl") = value.data();
  }

 private:
  void operator=(const WebPropertySummary&);
};  // WebPropertySummary
}  // namespace google_analytics_api
#endif  // GOOGLE_ANALYTICS_API_WEB_PROPERTY_SUMMARY_H_
