// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Analytics API (analytics/v3)
// Generated from:
//   Version: v3
//   Revision: 20170807
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_ANALYTICS_API_WEBPROPERTY_H_
#define  GOOGLE_ANALYTICS_API_WEBPROPERTY_H_

#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/client/util/date_time.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_analytics_api {
using namespace googleapis;

/**
 * JSON template for an Analytics web property.
 *
 * @ingroup DataObject
 */
class Webproperty : public client::JsonCppData {
 public:
  /**
   * Child link for this web property. Points to the list of views (profiles)
   * for this web property.
   *
   * @ingroup DataObject
   */
  class WebpropertyChildLink : public client::JsonCppData {
   public:
    /**
     * Creates a new default instance.
     *
     * @return Ownership is passed back to the caller.
     */
    static WebpropertyChildLink* New();

    /**
     * Standard constructor for an immutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit WebpropertyChildLink(const Json::Value& storage);

    /**
     * Standard constructor for a mutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit WebpropertyChildLink(Json::Value* storage);

    /**
     * Standard destructor.
     */
    virtual ~WebpropertyChildLink();

    /**
     * Returns a string denoting the type of this data object.
     *
     * @return <code>google_analytics_api::WebpropertyChildLink</code>
     */
    const char* GetTypeName() const {
      return "google_analytics_api::WebpropertyChildLink";
    }

    /**
     * Determine if the '<code>href</code>' attribute was set.
     *
     * @return true if the '<code>href</code>' attribute was set.
     */
    bool has_href() const {
      return Storage().isMember("href");
    }

    /**
     * Clears the '<code>href</code>' attribute.
     */
    void clear_href() {
      MutableStorage()->removeMember("href");
    }


    /**
     * Get the value of the '<code>href</code>' attribute.
     */
    const StringPiece get_href() const {
      const Json::Value& v = Storage("href");
      if (v == Json::Value::null) return StringPiece("");
      return StringPiece(v.asCString());
    }

    /**
     * Change the '<code>href</code>' attribute.
     *
     * Link to the list of views (profiles) for this web property.
     *
     * @param[in] value The new value.
     */
    void set_href(const StringPiece& value) {
      *MutableStorage("href") = value.data();
    }

    /**
     * Determine if the '<code>type</code>' attribute was set.
     *
     * @return true if the '<code>type</code>' attribute was set.
     */
    bool has_type() const {
      return Storage().isMember("type");
    }

    /**
     * Clears the '<code>type</code>' attribute.
     */
    void clear_type() {
      MutableStorage()->removeMember("type");
    }


    /**
     * Get the value of the '<code>type</code>' attribute.
     */
    const StringPiece get_type() const {
      const Json::Value& v = Storage("type");
      if (v == Json::Value::null) return StringPiece("");
      return StringPiece(v.asCString());
    }

    /**
     * Change the '<code>type</code>' attribute.
     *
     * Type of the parent link. Its value is "analytics#profiles".
     *
     * @param[in] value The new value.
     */
    void set_type(const StringPiece& value) {
      *MutableStorage("type") = value.data();
    }

   private:
    void operator=(const WebpropertyChildLink&);
  };  // WebpropertyChildLink
  /**
   * Parent link for this web property. Points to the account to which this web
   * property belongs.
   *
   * @ingroup DataObject
   */
  class WebpropertyParentLink : public client::JsonCppData {
   public:
    /**
     * Creates a new default instance.
     *
     * @return Ownership is passed back to the caller.
     */
    static WebpropertyParentLink* New();

    /**
     * Standard constructor for an immutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit WebpropertyParentLink(const Json::Value& storage);

    /**
     * Standard constructor for a mutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit WebpropertyParentLink(Json::Value* storage);

    /**
     * Standard destructor.
     */
    virtual ~WebpropertyParentLink();

    /**
     * Returns a string denoting the type of this data object.
     *
     * @return <code>google_analytics_api::WebpropertyParentLink</code>
     */
    const char* GetTypeName() const {
      return "google_analytics_api::WebpropertyParentLink";
    }

    /**
     * Determine if the '<code>href</code>' attribute was set.
     *
     * @return true if the '<code>href</code>' attribute was set.
     */
    bool has_href() const {
      return Storage().isMember("href");
    }

    /**
     * Clears the '<code>href</code>' attribute.
     */
    void clear_href() {
      MutableStorage()->removeMember("href");
    }


    /**
     * Get the value of the '<code>href</code>' attribute.
     */
    const StringPiece get_href() const {
      const Json::Value& v = Storage("href");
      if (v == Json::Value::null) return StringPiece("");
      return StringPiece(v.asCString());
    }

    /**
     * Change the '<code>href</code>' attribute.
     *
     * Link to the account for this web property.
     *
     * @param[in] value The new value.
     */
    void set_href(const StringPiece& value) {
      *MutableStorage("href") = value.data();
    }

    /**
     * Determine if the '<code>type</code>' attribute was set.
     *
     * @return true if the '<code>type</code>' attribute was set.
     */
    bool has_type() const {
      return Storage().isMember("type");
    }

    /**
     * Clears the '<code>type</code>' attribute.
     */
    void clear_type() {
      MutableStorage()->removeMember("type");
    }


    /**
     * Get the value of the '<code>type</code>' attribute.
     */
    const StringPiece get_type() const {
      const Json::Value& v = Storage("type");
      if (v == Json::Value::null) return StringPiece("");
      return StringPiece(v.asCString());
    }

    /**
     * Change the '<code>type</code>' attribute.
     *
     * Type of the parent link. Its value is "analytics#account".
     *
     * @param[in] value The new value.
     */
    void set_type(const StringPiece& value) {
      *MutableStorage("type") = value.data();
    }

   private:
    void operator=(const WebpropertyParentLink&);
  };  // WebpropertyParentLink
  /**
   * Permissions the user has for this web property.
   *
   * @ingroup DataObject
   */
  class WebpropertyPermissions : public client::JsonCppData {
   public:
    /**
     * Creates a new default instance.
     *
     * @return Ownership is passed back to the caller.
     */
    static WebpropertyPermissions* New();

    /**
     * Standard constructor for an immutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit WebpropertyPermissions(const Json::Value& storage);

    /**
     * Standard constructor for a mutable data object instance.
     *
     * @param[in] storage  The underlying data storage for this instance.
     */
    explicit WebpropertyPermissions(Json::Value* storage);

    /**
     * Standard destructor.
     */
    virtual ~WebpropertyPermissions();

    /**
     * Returns a string denoting the type of this data object.
     *
     * @return <code>google_analytics_api::WebpropertyPermissions</code>
     */
    const char* GetTypeName() const {
      return "google_analytics_api::WebpropertyPermissions";
    }

    /**
     * Determine if the '<code>effective</code>' attribute was set.
     *
     * @return true if the '<code>effective</code>' attribute was set.
     */
    bool has_effective() const {
      return Storage().isMember("effective");
    }

    /**
     * Clears the '<code>effective</code>' attribute.
     */
    void clear_effective() {
      MutableStorage()->removeMember("effective");
    }


    /**
     * Get a reference to the value of the '<code>effective</code>' attribute.
     */
    const client::JsonCppArray<string > get_effective() const {
       const Json::Value& storage = Storage("effective");
      return client::JsonValueToCppValueHelper<client::JsonCppArray<string > >(storage);
    }

    /**
     * Gets a reference to a mutable value of the '<code>effective</code>'
     * property.
     *
     * All the permissions that the user has for this web property. These
     * include any implied permissions (e.g., EDIT implies VIEW) or inherited
     * permissions from the parent account.
     *
     * @return The result can be modified to change the attribute value.
     */
    client::JsonCppArray<string > mutable_effective() {
      Json::Value* storage = MutableStorage("effective");
      return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<string > >(storage);
    }

   private:
    void operator=(const WebpropertyPermissions&);
  };  // WebpropertyPermissions
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Webproperty* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Webproperty(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Webproperty(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Webproperty();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_analytics_api::Webproperty</code>
   */
  const char* GetTypeName() const {
    return "google_analytics_api::Webproperty";
  }

  /**
   * Determine if the '<code>accountId</code>' attribute was set.
   *
   * @return true if the '<code>accountId</code>' attribute was set.
   */
  bool has_account_id() const {
    return Storage().isMember("accountId");
  }

  /**
   * Clears the '<code>accountId</code>' attribute.
   */
  void clear_account_id() {
    MutableStorage()->removeMember("accountId");
  }


  /**
   * Get the value of the '<code>accountId</code>' attribute.
   */
  const StringPiece get_account_id() const {
    const Json::Value& v = Storage("accountId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>accountId</code>' attribute.
   *
   * Account ID to which this web property belongs.
   *
   * @param[in] value The new value.
   */
  void set_account_id(const StringPiece& value) {
    *MutableStorage("accountId") = value.data();
  }

  /**
   * Determine if the '<code>childLink</code>' attribute was set.
   *
   * @return true if the '<code>childLink</code>' attribute was set.
   */
  bool has_child_link() const {
    return Storage().isMember("childLink");
  }

  /**
   * Clears the '<code>childLink</code>' attribute.
   */
  void clear_child_link() {
    MutableStorage()->removeMember("childLink");
  }


  /**
   * Get a reference to the value of the '<code>childLink</code>' attribute.
   */
  const WebpropertyChildLink get_child_link() const {
     const Json::Value& storage = Storage("childLink");
    return client::JsonValueToCppValueHelper<WebpropertyChildLink >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>childLink</code>'
   * property.
   *
   * Child link for this web property. Points to the list of views (profiles)
   * for this web property.
   *
   * @return The result can be modified to change the attribute value.
   */
  WebpropertyChildLink mutable_childLink() {
    Json::Value* storage = MutableStorage("childLink");
    return client::JsonValueToMutableCppValueHelper<WebpropertyChildLink >(storage);
  }

  /**
   * Determine if the '<code>created</code>' attribute was set.
   *
   * @return true if the '<code>created</code>' attribute was set.
   */
  bool has_created() const {
    return Storage().isMember("created");
  }

  /**
   * Clears the '<code>created</code>' attribute.
   */
  void clear_created() {
    MutableStorage()->removeMember("created");
  }


  /**
   * Get the value of the '<code>created</code>' attribute.
   */
  client::DateTime get_created() const {
    const Json::Value& storage = Storage("created");
    return client::JsonValueToCppValueHelper<client::DateTime >(storage);
  }

  /**
   * Change the '<code>created</code>' attribute.
   *
   * Time this web property was created.
   *
   * @param[in] value The new value.
   */
  void set_created(client::DateTime value) {
    client::SetJsonValueFromCppValueHelper<client::DateTime >(
      value, MutableStorage("created"));
  }

  /**
   * Determine if the '<code>defaultProfileId</code>' attribute was set.
   *
   * @return true if the '<code>defaultProfileId</code>' attribute was set.
   */
  bool has_default_profile_id() const {
    return Storage().isMember("defaultProfileId");
  }

  /**
   * Clears the '<code>defaultProfileId</code>' attribute.
   */
  void clear_default_profile_id() {
    MutableStorage()->removeMember("defaultProfileId");
  }


  /**
   * Get the value of the '<code>defaultProfileId</code>' attribute.
   */
  int64 get_default_profile_id() const {
    const Json::Value& storage = Storage("defaultProfileId");
    return client::JsonValueToCppValueHelper<int64 >(storage);
  }

  /**
   * Change the '<code>defaultProfileId</code>' attribute.
   *
   * Default view (profile) ID.
   *
   * @param[in] value The new value.
   */
  void set_default_profile_id(int64 value) {
    client::SetJsonValueFromCppValueHelper<int64 >(
      value, MutableStorage("defaultProfileId"));
  }

  /**
   * Determine if the '<code>id</code>' attribute was set.
   *
   * @return true if the '<code>id</code>' attribute was set.
   */
  bool has_id() const {
    return Storage().isMember("id");
  }

  /**
   * Clears the '<code>id</code>' attribute.
   */
  void clear_id() {
    MutableStorage()->removeMember("id");
  }


  /**
   * Get the value of the '<code>id</code>' attribute.
   */
  const StringPiece get_id() const {
    const Json::Value& v = Storage("id");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>id</code>' attribute.
   *
   * Web property ID of the form UA-XXXXX-YY.
   *
   * @param[in] value The new value.
   */
  void set_id(const StringPiece& value) {
    *MutableStorage("id") = value.data();
  }

  /**
   * Determine if the '<code>industryVertical</code>' attribute was set.
   *
   * @return true if the '<code>industryVertical</code>' attribute was set.
   */
  bool has_industry_vertical() const {
    return Storage().isMember("industryVertical");
  }

  /**
   * Clears the '<code>industryVertical</code>' attribute.
   */
  void clear_industry_vertical() {
    MutableStorage()->removeMember("industryVertical");
  }


  /**
   * Get the value of the '<code>industryVertical</code>' attribute.
   */
  const StringPiece get_industry_vertical() const {
    const Json::Value& v = Storage("industryVertical");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>industryVertical</code>' attribute.
   *
   * The industry vertical/category selected for this web property.
   *
   * @param[in] value The new value.
   */
  void set_industry_vertical(const StringPiece& value) {
    *MutableStorage("industryVertical") = value.data();
  }

  /**
   * Determine if the '<code>internalWebPropertyId</code>' attribute was set.
   *
   * @return true if the '<code>internalWebPropertyId</code>' attribute was set.
   */
  bool has_internal_web_property_id() const {
    return Storage().isMember("internalWebPropertyId");
  }

  /**
   * Clears the '<code>internalWebPropertyId</code>' attribute.
   */
  void clear_internal_web_property_id() {
    MutableStorage()->removeMember("internalWebPropertyId");
  }


  /**
   * Get the value of the '<code>internalWebPropertyId</code>' attribute.
   */
  const StringPiece get_internal_web_property_id() const {
    const Json::Value& v = Storage("internalWebPropertyId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>internalWebPropertyId</code>' attribute.
   *
   * Internal ID for this web property.
   *
   * @param[in] value The new value.
   */
  void set_internal_web_property_id(const StringPiece& value) {
    *MutableStorage("internalWebPropertyId") = value.data();
  }

  /**
   * Determine if the '<code>kind</code>' attribute was set.
   *
   * @return true if the '<code>kind</code>' attribute was set.
   */
  bool has_kind() const {
    return Storage().isMember("kind");
  }

  /**
   * Clears the '<code>kind</code>' attribute.
   */
  void clear_kind() {
    MutableStorage()->removeMember("kind");
  }


  /**
   * Get the value of the '<code>kind</code>' attribute.
   */
  const StringPiece get_kind() const {
    const Json::Value& v = Storage("kind");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>kind</code>' attribute.
   *
   * Resource type for Analytics WebProperty.
   *
   * @param[in] value The new value.
   */
  void set_kind(const StringPiece& value) {
    *MutableStorage("kind") = value.data();
  }

  /**
   * Determine if the '<code>level</code>' attribute was set.
   *
   * @return true if the '<code>level</code>' attribute was set.
   */
  bool has_level() const {
    return Storage().isMember("level");
  }

  /**
   * Clears the '<code>level</code>' attribute.
   */
  void clear_level() {
    MutableStorage()->removeMember("level");
  }


  /**
   * Get the value of the '<code>level</code>' attribute.
   */
  const StringPiece get_level() const {
    const Json::Value& v = Storage("level");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>level</code>' attribute.
   *
   * Level for this web property. Possible values are STANDARD or PREMIUM.
   *
   * @param[in] value The new value.
   */
  void set_level(const StringPiece& value) {
    *MutableStorage("level") = value.data();
  }

  /**
   * Determine if the '<code>name</code>' attribute was set.
   *
   * @return true if the '<code>name</code>' attribute was set.
   */
  bool has_name() const {
    return Storage().isMember("name");
  }

  /**
   * Clears the '<code>name</code>' attribute.
   */
  void clear_name() {
    MutableStorage()->removeMember("name");
  }


  /**
   * Get the value of the '<code>name</code>' attribute.
   */
  const StringPiece get_name() const {
    const Json::Value& v = Storage("name");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>name</code>' attribute.
   *
   * Name of this web property.
   *
   * @param[in] value The new value.
   */
  void set_name(const StringPiece& value) {
    *MutableStorage("name") = value.data();
  }

  /**
   * Determine if the '<code>parentLink</code>' attribute was set.
   *
   * @return true if the '<code>parentLink</code>' attribute was set.
   */
  bool has_parent_link() const {
    return Storage().isMember("parentLink");
  }

  /**
   * Clears the '<code>parentLink</code>' attribute.
   */
  void clear_parent_link() {
    MutableStorage()->removeMember("parentLink");
  }


  /**
   * Get a reference to the value of the '<code>parentLink</code>' attribute.
   */
  const WebpropertyParentLink get_parent_link() const {
     const Json::Value& storage = Storage("parentLink");
    return client::JsonValueToCppValueHelper<WebpropertyParentLink >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>parentLink</code>'
   * property.
   *
   * Parent link for this web property. Points to the account to which this web
   * property belongs.
   *
   * @return The result can be modified to change the attribute value.
   */
  WebpropertyParentLink mutable_parentLink() {
    Json::Value* storage = MutableStorage("parentLink");
    return client::JsonValueToMutableCppValueHelper<WebpropertyParentLink >(storage);
  }

  /**
   * Determine if the '<code>permissions</code>' attribute was set.
   *
   * @return true if the '<code>permissions</code>' attribute was set.
   */
  bool has_permissions() const {
    return Storage().isMember("permissions");
  }

  /**
   * Clears the '<code>permissions</code>' attribute.
   */
  void clear_permissions() {
    MutableStorage()->removeMember("permissions");
  }


  /**
   * Get a reference to the value of the '<code>permissions</code>' attribute.
   */
  const WebpropertyPermissions get_permissions() const {
     const Json::Value& storage = Storage("permissions");
    return client::JsonValueToCppValueHelper<WebpropertyPermissions >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>permissions</code>'
   * property.
   *
   * Permissions the user has for this web property.
   *
   * @return The result can be modified to change the attribute value.
   */
  WebpropertyPermissions mutable_permissions() {
    Json::Value* storage = MutableStorage("permissions");
    return client::JsonValueToMutableCppValueHelper<WebpropertyPermissions >(storage);
  }

  /**
   * Determine if the '<code>profileCount</code>' attribute was set.
   *
   * @return true if the '<code>profileCount</code>' attribute was set.
   */
  bool has_profile_count() const {
    return Storage().isMember("profileCount");
  }

  /**
   * Clears the '<code>profileCount</code>' attribute.
   */
  void clear_profile_count() {
    MutableStorage()->removeMember("profileCount");
  }


  /**
   * Get the value of the '<code>profileCount</code>' attribute.
   */
  int32 get_profile_count() const {
    const Json::Value& storage = Storage("profileCount");
    return client::JsonValueToCppValueHelper<int32 >(storage);
  }

  /**
   * Change the '<code>profileCount</code>' attribute.
   *
   * View (Profile) count for this web property.
   *
   * @param[in] value The new value.
   */
  void set_profile_count(int32 value) {
    client::SetJsonValueFromCppValueHelper<int32 >(
      value, MutableStorage("profileCount"));
  }

  /**
   * Determine if the '<code>selfLink</code>' attribute was set.
   *
   * @return true if the '<code>selfLink</code>' attribute was set.
   */
  bool has_self_link() const {
    return Storage().isMember("selfLink");
  }

  /**
   * Clears the '<code>selfLink</code>' attribute.
   */
  void clear_self_link() {
    MutableStorage()->removeMember("selfLink");
  }


  /**
   * Get the value of the '<code>selfLink</code>' attribute.
   */
  const StringPiece get_self_link() const {
    const Json::Value& v = Storage("selfLink");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>selfLink</code>' attribute.
   *
   * Link for this web property.
   *
   * @param[in] value The new value.
   */
  void set_self_link(const StringPiece& value) {
    *MutableStorage("selfLink") = value.data();
  }

  /**
   * Determine if the '<code>starred</code>' attribute was set.
   *
   * @return true if the '<code>starred</code>' attribute was set.
   */
  bool has_starred() const {
    return Storage().isMember("starred");
  }

  /**
   * Clears the '<code>starred</code>' attribute.
   */
  void clear_starred() {
    MutableStorage()->removeMember("starred");
  }


  /**
   * Get the value of the '<code>starred</code>' attribute.
   */
  bool get_starred() const {
    const Json::Value& storage = Storage("starred");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>starred</code>' attribute.
   *
   * Indicates whether this web property is starred or not.
   *
   * @param[in] value The new value.
   */
  void set_starred(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("starred"));
  }

  /**
   * Determine if the '<code>updated</code>' attribute was set.
   *
   * @return true if the '<code>updated</code>' attribute was set.
   */
  bool has_updated() const {
    return Storage().isMember("updated");
  }

  /**
   * Clears the '<code>updated</code>' attribute.
   */
  void clear_updated() {
    MutableStorage()->removeMember("updated");
  }


  /**
   * Get the value of the '<code>updated</code>' attribute.
   */
  client::DateTime get_updated() const {
    const Json::Value& storage = Storage("updated");
    return client::JsonValueToCppValueHelper<client::DateTime >(storage);
  }

  /**
   * Change the '<code>updated</code>' attribute.
   *
   * Time this web property was last modified.
   *
   * @param[in] value The new value.
   */
  void set_updated(client::DateTime value) {
    client::SetJsonValueFromCppValueHelper<client::DateTime >(
      value, MutableStorage("updated"));
  }

  /**
   * Determine if the '<code>websiteUrl</code>' attribute was set.
   *
   * @return true if the '<code>websiteUrl</code>' attribute was set.
   */
  bool has_website_url() const {
    return Storage().isMember("websiteUrl");
  }

  /**
   * Clears the '<code>websiteUrl</code>' attribute.
   */
  void clear_website_url() {
    MutableStorage()->removeMember("websiteUrl");
  }


  /**
   * Get the value of the '<code>websiteUrl</code>' attribute.
   */
  const StringPiece get_website_url() const {
    const Json::Value& v = Storage("websiteUrl");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>websiteUrl</code>' attribute.
   *
   * Website url for this web property.
   *
   * @param[in] value The new value.
   */
  void set_website_url(const StringPiece& value) {
    *MutableStorage("websiteUrl") = value.data();
  }

 private:
  void operator=(const Webproperty&);
};  // Webproperty
}  // namespace google_analytics_api
#endif  // GOOGLE_ANALYTICS_API_WEBPROPERTY_H_
