// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Analytics API (analytics/v3)
// Description:
//   Views and manages your Google Analytics data.
// Classes:
//   Webproperty
// Documentation:
//   https://developers.google.com/analytics/

#include "google/analytics_api/webproperty.h"
#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/client/util/date_time.h"
#include "googleapis/strings/stringpiece.h"


#include <string>
#include "googleapis/strings/strcat.h"

namespace google_analytics_api {
using namespace googleapis;



// Object factory method (static).
Webproperty::WebpropertyChildLink* Webproperty::WebpropertyChildLink::New() {
  return new client::JsonCppCapsule<WebpropertyChildLink>;
}

// Standard immutable constructor.
Webproperty::WebpropertyChildLink::WebpropertyChildLink(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
Webproperty::WebpropertyChildLink::WebpropertyChildLink(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
Webproperty::WebpropertyChildLink::~WebpropertyChildLink() {
}

// Properties.

// Object factory method (static).
Webproperty::WebpropertyParentLink* Webproperty::WebpropertyParentLink::New() {
  return new client::JsonCppCapsule<WebpropertyParentLink>;
}

// Standard immutable constructor.
Webproperty::WebpropertyParentLink::WebpropertyParentLink(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
Webproperty::WebpropertyParentLink::WebpropertyParentLink(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
Webproperty::WebpropertyParentLink::~WebpropertyParentLink() {
}

// Properties.

// Object factory method (static).
Webproperty::WebpropertyPermissions* Webproperty::WebpropertyPermissions::New() {
  return new client::JsonCppCapsule<WebpropertyPermissions>;
}

// Standard immutable constructor.
Webproperty::WebpropertyPermissions::WebpropertyPermissions(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
Webproperty::WebpropertyPermissions::WebpropertyPermissions(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
Webproperty::WebpropertyPermissions::~WebpropertyPermissions() {
}

// Properties.
// Object factory method (static).
Webproperty* Webproperty::New() {
  return new client::JsonCppCapsule<Webproperty>;
}

// Standard immutable constructor.
Webproperty::Webproperty(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
Webproperty::Webproperty(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
Webproperty::~Webproperty() {
}

// Properties.
}  // namespace google_analytics_api
